name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build
    - name: Install gems
      run: docker-compose run --rm ruby bundle
    - name: Rubocop
      run: docker-compose run --rm ruby bundle exec rubocop
    - name: Tests
      run: docker-compose run --rm ruby bundle exec rake test
